# **PART A**

1. Load and Print Data

In [ ]:
def load_and_print_data(file_path):
    with open(file_path, 'r') as file:
        data = file.read()
    print(data[:500])
    return data

data = load_and_print_data("/content/sample_data/twitter.txt")

How are you? Btw thanks for the RT. You gonna be in DC anytime soon? Love to see you. Been way, way too long.
When you meet someone special... you'll know. Your heart will beat more rapidly and you'll smile for no reason.
they've decided its more fun if I don't.
So Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)
Words from a complete stranger! Made my birthday even better :)
First Cubs game ever! Wrigley field is gorgeous. This is perfect. Go Cubs Go!
i no! i ge


2. Split to Sentences

In [ ]:
import re

def split_to_sentences(data):
    sentences = re.split(r'[.!?]+', data)
    return sentences

sentences = split_to_sentences(data)
print(sentences[:100])

['How are you', ' Btw thanks for the RT', ' You gonna be in DC anytime soon', ' Love to see you', ' Been way, way too long', '\nWhen you meet someone special', " you'll know", " Your heart will beat more rapidly and you'll smile for no reason", "\nthey've decided its more fun if I don't", '\nSo Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)\nWords from a complete stranger', ' Made my birthday even better :)\nFirst Cubs game ever', ' Wrigley field is gorgeous', ' This is perfect', ' Go Cubs Go', '\ni no', ' i get another day off from skool due to the wonderful snow (: and THIS wakes me up', "damn thing\nI'm coo", ' Jus at work hella tired r u ever in cali\nThe new sundrop commercial ', 'hehe love at first sight\nwe need to reconnect THIS WEEK\nI always wonder how the guys on the auctions shows learned to talk so fast', ' all I hear is djsosnekspqnslanskam', '\nDammnnnnn what a catch\nsuch a great picture', ' The green shirt totally brings out your eyes

3. Tokenize Sentences

In [ ]:
import nltk
nltk.download('punkt')

def tokenize_sentences(sentences):
    tokenized_sentences = [nltk.word_tokenize(sentence) for sentence in sentences]
    return tokenized_sentences

tokenized_sentences = tokenize_sentences(sentences)
print(tokenized_sentences[:1000])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[['How', 'are', 'you'], ['Btw', 'thanks', 'for', 'the', 'RT'], ['You', 'gon', 'na', 'be', 'in', 'DC', 'anytime', 'soon'], ['Love', 'to', 'see', 'you'], ['Been', 'way', ',', 'way', 'too', 'long'], ['When', 'you', 'meet', 'someone', 'special'], ['you', "'ll", 'know'], ['Your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'I', 'do', "n't"], ['So', 'Tired', 'D', ';', 'Played', 'Lazer', 'Tag', '&', 'Ran', 'A', 'LOT', 'D', ';', 'Ughh', 'Going', 'To', 'Sleep', 'Like', 'In', '5', 'Minutes', ';', ')', 'Words', 'from', 'a', 'complete', 'stranger'], ['Made', 'my', 'birthday', 'even', 'better', ':', ')', 'First', 'Cubs', 'game', 'ever'], ['Wrigley', 'field', 'is', 'gorgeous'], ['This', 'is', 'perfect'], ['Go', 'Cubs', 'Go'], ['i', 'no'], ['i', 'get', 'another', 'day', 'off', 'from', 'skool', 'due', 'to', 'the', 'wonderful', 'snow', '(', ':', 'and', 'THIS', 'wakes', 'me', 'up'], ['damn', 'thi

4. Tokenize Data

In [ ]:
def tokenize_data(data):
    sentences = split_to_sentences(data)
    tokenized_sentences = tokenize_sentences(sentences)
    return tokenized_sentences

tokenized_data = tokenize_data(data)
print(tokenized_data[:1000])

[['How', 'are', 'you'], ['Btw', 'thanks', 'for', 'the', 'RT'], ['You', 'gon', 'na', 'be', 'in', 'DC', 'anytime', 'soon'], ['Love', 'to', 'see', 'you'], ['Been', 'way', ',', 'way', 'too', 'long'], ['When', 'you', 'meet', 'someone', 'special'], ['you', "'ll", 'know'], ['Your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'I', 'do', "n't"], ['So', 'Tired', 'D', ';', 'Played', 'Lazer', 'Tag', '&', 'Ran', 'A', 'LOT', 'D', ';', 'Ughh', 'Going', 'To', 'Sleep', 'Like', 'In', '5', 'Minutes', ';', ')', 'Words', 'from', 'a', 'complete', 'stranger'], ['Made', 'my', 'birthday', 'even', 'better', ':', ')', 'First', 'Cubs', 'game', 'ever'], ['Wrigley', 'field', 'is', 'gorgeous'], ['This', 'is', 'perfect'], ['Go', 'Cubs', 'Go'], ['i', 'no'], ['i', 'get', 'another', 'day', 'off', 'from', 'skool', 'due', 'to', 'the', 'wonderful', 'snow', '(', ':', 'and', 'THIS', 'wakes', 'me', 'up'], ['damn', 'thi

5. Test / Train Split


In [ ]:
from sklearn.model_selection import train_test_split

def split_data(tokenized_data):
    X_train, X_test, y_train, y_test = train_test_split(tokenized_data, tokenized_data, test_size=0.2, random_state=42)
    return X_train, X_test

X_train, X_test = split_data(tokenized_data)
print("Training Data:", X_train[:100])
print("Test Data:", X_test[:100])

Training Data: [['Spot', 'trending', 'now', 'in', 'Chicago', ',', 'IL', ':', 'Bella', 'Bacinos', '-', 'Italian', '(', 'live', 'updates', ')', 'maybe', 'you', 'should', 'try', 'rehab'], ['DON', '’', 'T', 'use', 'cleaning', 'products', 'on', 'or', 'near', 'your', 'natural', 'stone', 'unless', 'the', 'label', 'specifies', 'that', 'it', 'is', 'safe', 'for', 'it'], ['yes'], ['yes', ',', 'tomorrow'], ['Ma', 'girl', 'just', 'got', 'her', 'Twitter', 'page', 'rock', 'she', 'need', 'sum', '#', 'followers', '>', '>', '>', '>', '>', '>', '>', '>', '#', 'ff', '#', 'teamfollowback', 'show', 'her', 'how', 'we', 'roll', 'One', 'of', 'our', 'girls', 'is', 'in', 'the', 'Military'], ['He', 'was', 'a', 'lunatic'], ['Those', 'constant', 'requests', 'are', 'why', 'Jasika', 'left'], ['I', 'miss', 'you', 'guys', 'so', 'much', '<', '/3', 'It', 'is', 'May'], ['you', 'have', 'no', 'idea', 'how', 'happy', 'I', 'am', 'you', 'followed', 'me'], [':', ')', 'You', 'know', 'I', 'stay', 'blunted', 'SHIT', 'so', 'big', '

6. Count Words


In [ ]:
from collections import Counter

def count_words(tokenized_sentences):
    word_counts = Counter()
    for sentence in tokenized_sentences:
        word_counts.update(sentence)
    return word_counts

word_counts = count_words(tokenized_data)
print(word_counts)

Counter({'the': 17122, 'I': 16211, 'to': 15455, ',': 15289, 'a': 11699, 'you': 10656, 'and': 8153, ':': 7727, 'for': 7534, 'in': 7274, 'is': 7274, 'of': 7118, 'it': 6412, "'s": 5995, '#': 5389, 'on': 5325, 'my': 5007, 'that': 4836, "n't": 4187, ')': 4076, 'me': 3984, 'be': 3675, 'at': 3610, 'with': 3385, 'have': 3234, '``': 3131, 'are': 3124, 'your': 3123, 'do': 3015, 'this': 2771, "'m": 2595, 'so': 2571, "''": 2428, 'like': 2390, 'i': 2363, 'was': 2355, 'just': 2262, 'out': 2241, 'not': 2222, 'up': 2189, '&': 2160, 'all': 2145, 'but': 2108, 'we': 2078, 'get': 2011, '(': 2003, '-': 1993, 'can': 1788, 'RT': 1771, 'will': 1763, 'about': 1760, 'The': 1713, 'what': 1658, 'love': 1632, 'from': 1615, 'know': 1555, 'good': 1534, 'one': 1476, 'day': 1462, 'now': 1461, 'You': 1422, 'if': 1398, 'u': 1357, 'It': 1357, 'time': 1341, 'an': 1336, 'today': 1316, 'they': 1313, 'when': 1305, 'or': 1303, 'as': 1261, 'We': 1247, "'re": 1241, 'go': 1227, 'by': 1193, 'more': 1192, 'great': 1192, 'Thanks': 

7. Words with N Frequency


In [ ]:
def get_closed_vocabulary(tokenized_sentences, threshold):
    word_counts = count_words(tokenized_sentences)
    closed_vocabulary = set(word for word, count in word_counts.items() if count >= threshold)
    return closed_vocabulary

closed_vocabulary = get_closed_vocabulary(tokenized_data, 2)
print(closed_vocabulary)

{'CHRISTMAS', 'Tools', 'Landing', 'lights', 'NJ', 'Skills', 'Hoes', 'HANDLE', 'outperform', 'Remind', 'Godfather', 'element', 'refuses', 'Elliot', 'Bruno', 'conscientious', 'Middle', 'Remodeling', 'berries', 'Earl', 'movements', 'thriller', 'Northwest', 'Titanic', 'unreasonable', '405', 'wiggle', 'DJ', 'lung', 'insomnia', 'materials', 'amazes', 'span', 'Einstein', 'thousand', 'superhero', 'Pics', 'rumored', 'brick', 'Means', 'dining', 'crawl', 'snake', 'Laurie', 'idgaf', 'puzzled', 'HEAR', 'PPV', 'JB', 'tlking', 'Ross', 'ghost', 'Corps', 'Latin', 'Kodak', 'Chaz', 'RUNNING', 'barbecue', 'reps', 'lion', 'Miller', 'BEEN', 'biology', 'abundantly', 'quarter', 'Wolfe', 'Conrad', 'rumor', 'lacks', 'BBA', 'Melancholia', 'pressing', 'shake', 'pa', 'Ari', '1994', '150,000', 'WORTH', 'Trading', 'disco', 'users', 'china', 'Salute', 'cooling', 'homes', 'Hanks', 'brace', '3/24', 'financial', 'implemented', 'dealing', 'Westbrook', 'Stack', 'HALF', 'innovators', 'subscription', 'strikes', 'walking', '

8. Replace OOV with UNK

In [ ]:
def replace_oov_with_unk(tokenized_sentences, vocabulary, unknown_token='<unk>'):
    replaced_sentences = []
    for sentence in tokenized_sentences:
        replaced_sentence = [word if word in vocabulary else unknown_token for word in sentence]
        replaced_sentences.append(replaced_sentence)
    return replaced_sentences

replaced_tokenized_data = replace_oov_with_unk(tokenized_data, closed_vocabulary)
print(replaced_tokenized_data[:1000])

[['How', 'are', 'you'], ['Btw', 'thanks', 'for', 'the', 'RT'], ['You', 'gon', 'na', 'be', 'in', 'DC', 'anytime', 'soon'], ['Love', 'to', 'see', 'you'], ['Been', 'way', ',', 'way', 'too', 'long'], ['When', 'you', 'meet', 'someone', 'special'], ['you', "'ll", 'know'], ['Your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'I', 'do', "n't"], ['So', 'Tired', 'D', ';', 'Played', '<unk>', 'Tag', '&', 'Ran', 'A', 'LOT', 'D', ';', '<unk>', 'Going', 'To', 'Sleep', 'Like', 'In', '5', 'Minutes', ';', ')', 'Words', 'from', 'a', 'complete', 'stranger'], ['Made', 'my', 'birthday', 'even', 'better', ':', ')', 'First', 'Cubs', 'game', 'ever'], ['Wrigley', 'field', 'is', 'gorgeous'], ['This', 'is', 'perfect'], ['Go', 'Cubs', 'Go'], ['i', 'no'], ['i', 'get', 'another', 'day', 'off', 'from', 'skool', 'due', 'to', 'the', 'wonderful', 'snow', '(', ':', 'and', 'THIS', 'wakes', 'me', 'up'], ['damn', 'th

9. Pre-process Data

In [ ]:
def preprocess_data(train_data, test_data, threshold):
    closed_vocabulary = get_closed_vocabulary(train_data + test_data, threshold)
    train_data_replaced = replace_oov_with_unk(train_data, closed_vocabulary)
    test_data_replaced = replace_oov_with_unk(test_data, closed_vocabulary)
    return train_data_replaced, test_data_replaced, closed_vocabulary

train_data_replaced, test_data_replaced, vocabulary = preprocess_data(X_train, X_test, 2)
print("Preprocessed Training Data:", train_data_replaced[:1000])
print("Preprocessed Test Data:", test_data_replaced[:1000])
print("Vocabulary:", vocabulary)

Preprocessed Training Data: [['Spot', 'trending', 'now', 'in', 'Chicago', ',', 'IL', ':', 'Bella', '<unk>', '-', 'Italian', '(', 'live', 'updates', ')', 'maybe', 'you', 'should', 'try', 'rehab'], ['DON', '’', 'T', 'use', 'cleaning', 'products', 'on', 'or', 'near', 'your', 'natural', 'stone', 'unless', 'the', 'label', '<unk>', 'that', 'it', 'is', 'safe', 'for', 'it'], ['yes'], ['yes', ',', 'tomorrow'], ['Ma', 'girl', 'just', 'got', 'her', 'Twitter', 'page', 'rock', 'she', 'need', 'sum', '#', 'followers', '>', '>', '>', '>', '>', '>', '>', '>', '#', 'ff', '#', 'teamfollowback', 'show', 'her', 'how', 'we', 'roll', 'One', 'of', 'our', 'girls', 'is', 'in', 'the', 'Military'], ['He', 'was', 'a', '<unk>'], ['Those', 'constant', 'requests', 'are', 'why', '<unk>', 'left'], ['I', 'miss', 'you', 'guys', 'so', 'much', '<', '/3', 'It', 'is', 'May'], ['you', 'have', 'no', 'idea', 'how', 'happy', 'I', 'am', 'you', 'followed', 'me'], [':', ')', 'You', 'know', 'I', 'stay', '<unk>', 'SHIT', 'so', 'big',

# **PART B**

10. Count N-Grams

In [ ]:
from collections import defaultdict
import itertools

def add_start_end_tokens(sentences, n):
    start_token = "<s>"
    end_token = "<e>"
    padded_sentences = [
        [start_token] * (n-1) + sentence + [end_token] for sentence in sentences
    ]
    return padded_sentences

def count_ngrams(sentences, n):
    ngrams = defaultdict(int)
    for sentence in sentences:
        for i in range(len(sentence) - n + 1):
            ngram = tuple(sentence[i:i+n])
            ngrams[ngram] += 1
    return ngrams

n = 2
padded_tokenized_sentences = add_start_end_tokens(tokenized_sentences, n)
bigrams = count_ngrams(padded_tokenized_sentences, n)
print(list(bigrams.items())[:10])

[(('<s>', 'How'), 329), (('How', 'are'), 49), (('are', 'you'), 352), (('you', '<e>'), 1066), (('<s>', 'Btw'), 10), (('Btw', 'thanks'), 1), (('thanks', 'for'), 283), (('for', 'the'), 1420), (('the', 'RT'), 76), (('RT', '<e>'), 72)]


11. Estimate Probability of Single Word

In [ ]:
def estimate_probability(word, prev_ngram, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    ngram = tuple(prev_ngram)
    nplus1gram = tuple(prev_ngram + [word])
    ngram_count = ngram_counts[ngram]
    nplus1gram_count = nplus1gram_counts[nplus1gram]
    probability = (nplus1gram_count + k) / (ngram_count + k * vocab_size)
    return probability

word = 'new'
prev_ngram = ['<s>']
vocab_size = len(vocabulary)
nplus1grams = count_ngrams(padded_tokenized_sentences, n+1)
probability = estimate_probability(word, prev_ngram, bigrams, nplus1grams, vocab_size)
print("Probability:", probability)

Probability: 4.804458537522821e-05


12. Estimate Probability of All Words

In [ ]:
def estimate_all_probabilities(prev_ngram, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    probabilities = {}
    for word in vocabulary:
        probabilities[word] = estimate_probability(word, prev_ngram, ngram_counts, nplus1gram_counts, vocab_size, k)
    return probabilities

all_probabilities = estimate_all_probabilities(prev_ngram, bigrams, nplus1grams, vocab_size)
print(list(all_probabilities.items())[:10])

[('CHRISTMAS', 4.804458537522821e-05), ('Tools', 4.804458537522821e-05), ('Landing', 4.804458537522821e-05), ('lights', 4.804458537522821e-05), ('NJ', 4.804458537522821e-05), ('Skills', 4.804458537522821e-05), ('Hoes', 4.804458537522821e-05), ('HANDLE', 4.804458537522821e-05), ('Remind', 4.804458537522821e-05), ('outperform', 4.804458537522821e-05)]


13. Make Count Matrix

In [ ]:
def make_count_matrix(nplus1gram_counts, vocab):
    vocab_size = len(vocab)
    vocab_list = list(vocab)
    index = {word: i for i, word in enumerate(vocab_list)}
    count_matrix = np.zeros((vocab_size, vocab_size), dtype=int)

    for nplus1gram, count in nplus1gram_counts.items():
        prev_ngram = tuple(nplus1gram[:-1])
        word = nplus1gram[-1]
        if prev_ngram[-1] in index and word in index:
            row = index[prev_ngram[-1]]
            col = index[word]
            count_matrix[row][col] = count

    print("Count Matrix:")
    print(count_matrix)

    return count_matrix

count_matrix = make_count_matrix(nplus1grams, vocabulary)

Count Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


14. Make Probability Matrix

In [ ]:
import numpy as np

def make_probability_matrix(n_plus_1_gram_counts, vocabulary, k=1):
    vocab_list = list(vocabulary)
    vocab_size = len(vocab_list)
    count_matrix = np.zeros((vocab_size, vocab_size))

    for ngram, count in n_plus_1_gram_counts.items():
        ngram_split = ngram.split()
        if len(ngram_split) == 2:
            try:
                i = vocab_list.index(ngram_split[0])
                j = vocab_list.index(ngram_split[1])
                count_matrix[i, j] = count
            except ValueError:
                pass
    smoothed_count_matrix = count_matrix + k
    row_sums = smoothed_count_matrix.sum(axis=1, keepdims=True)

    with np.errstate(divide='ignore', invalid='ignore'):
        probability_matrix = np.divide(smoothed_count_matrix, row_sums, where=row_sums != 0)

    return probability_matrix
print("Probability Matrix:\n", probability_matrix)

Probability Matrix:
 [[0.125      0.125      0.125      0.125      0.125      0.125
  0.25      ]
 [0.125      0.125      0.125      0.125      0.125      0.25
  0.125     ]
 [0.25       0.125      0.125      0.125      0.125      0.125
  0.125     ]
 [0.125      0.125      0.125      0.125      0.25       0.125
  0.125     ]
 [0.125      0.25       0.125      0.125      0.125      0.125
  0.125     ]
 [0.125      0.125      0.25       0.125      0.125      0.125
  0.125     ]
 [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
  0.14285714]]


# **PART C**

15. Calculate Perplexity

In [ ]:
import numpy as np
from collections import Counter

def calculate_perplexity(sentence, ngram_counts, n_plus_1_gram_counts, vocabulary_size, k=0.01):
    n = len(next(iter(ngram_counts)))
    sentence = ["<s>"] * (n-1) + sentence + ["</s>"]
    N = len(sentence)
    log_prob = 0.0
    for i in range(n-1, N):
        previous_ngram = sentence[i-n+1:i]
        word = sentence[i]
        probability = estimate_probability(word, previous_ngram, ngram_counts, n_plus_1_gram_counts, vocabulary_size, k)
        log_prob += np.log(probability)
    perplexity = np.exp(-log_prob / (N - (n-1)))
    return perplexity

sample_sentence = ["I", "am", "doing", "project"]

unigram = count_ngrams(sample_sentence, 1)
bigram = count_ngrams(sample_sentence, 2)

perplexity = calculate_perplexity(sample_sentence, unigram, bigram, len(sample_sentence), k=0.01)
print("Perplexity:", perplexity)

Perplexity: 4.0


# **PART D**

16. Suggest a Word

In [ ]:
def suggest_word(prev_tokens, ngram_counts, nplus1gram_counts, vocab_size, k=1, start_with=None):
    probabilities = estimate_all_probabilities(prev_tokens, ngram_counts, nplus1gram_counts, vocab_size, k)

    if start_with:
        probabilities = {word: prob for word, prob in probabilities.items() if word.startswith(start_with)}

    suggestion = max(probabilities, key=probabilities.get)
    max_probability = probabilities[suggestion]

    return suggestion, max_probability

suggestion, max_probability = suggest_word(prev_tokens, bigrams, nplus1grams, vocab_size, k=1, start_with=None)
print(f"Suggestion: {suggestion}, Max Probability: {max_probability}")

Suggestion: get, Max Probability: 0.0004797313504437515


17. Get Suggestions

In [ ]:
def get_all_suggestions(prev_tokens, ngram_counts, nplus1gram_counts, vocabulary, k=1, start_with=None):
    probabilities = estimate_all_probabilities(prev_tokens, ngram_counts, nplus1gram_counts, len(vocabulary), k)

    if start_with:
        probabilities = {word: prob for word, prob in probabilities.items() if word.startswith(start_with)}

    sorted_suggestions = sorted(probabilities.items(), key=lambda item: item[1], reverse=True)

    return sorted_suggestions

all_suggestions = get_all_suggestions(prev_tokens, bigrams, nplus1grams, vocabulary, k=1, start_with=None)
print("All Suggestions:")
for word, prob in all_suggestions[:10]:
    print(f"Word: {word}, Probability: {prob}")

All Suggestions:
Word: get, Probability: 0.0004797313504437515
Word: go, Probability: 0.0001918925401775006
Word: have, Probability: 0.0001918925401775006
Word: be, Probability: 0.00014391940513312545
Word: please, Probability: 9.59462700887503e-05
Word: call, Probability: 9.59462700887503e-05
Word: link, Probability: 9.59462700887503e-05
Word: spend, Probability: 9.59462700887503e-05
Word: meet, Probability: 9.59462700887503e-05
Word: still, Probability: 9.59462700887503e-05
